---
- name: Install required software
  apt: name={{ item }} state=present
  become: true
  with_items:
    - apache2
    - php-mysql
    - php
    - libapache2-mod-php
    - php-mcrypt
    - python-mysqldb

- name: Install php extensions
  apt: name={{ item }} state=present
  become: true
  with_items:
    - php-gd 
    - libssh2-php
