---
- name: Install required software
  yum: name={{ item }} state=present
  become: true
  with_items:
    - apache2
    - php5-mysql
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - python-mysqldb

- name: Install php extensions
  yum: name={{ item }} state=present
  become: true
  with_items:
    - php5-gd 
    - libssh2-php
